<?php

return [
    "account_reg_log" => [
        "user_account",
        "device_id",
        "ip",
        "psw",
        "acc_type",
    ],
    "role_create_log" => [
        "device_id",
        "ip",
        "nick",
    ],
    "role_act_log" => [
        "device_id",
        "ip",
        "operation_code",
        "online_time",
    ],
    "item_change_log" => [
        "item_id",
        "change_type",
        "vip",
        "level",
        "change_num",
        "change_total",
        "operate_type",
        "goods_val",
        "extra",
    ],
    "recharge_log" => [
        "order_id",
        "sdk_order_id",
        "cost_type",
        "pay_money",
        "status",
        "pay_type",
        "good_list",
        "recharge_id",
    ],
    "user_change_log" => [
        "nick",
        "vip",
        "reborn",
        "level",
        "power",
        "status",
    ],
    "advise_log" => [
        "type",
        "content",
    ],
    "union_change_log" => [
        "union_id",
        "change_type",
        "union_name",
        "union_exp",
    ],
    "union_join_log" => [
        "union_id",
        "join_type",
    ],
    "online_log" => [
        "zone_id",
        "total_num",
        "ios_num",
        "android_num",
    ],
    "ranking_list_log" => [
        "zone_id",
        "rank_type",
        "ranking",
        "uid",
        "nick",
        "ranking_points",
        "rewards",
    ],
    "task_log" => [
        "task_id",
        "rewards",
        "extra",
    ],
    "summon_partner_log" => [
        "summon_id",
        "partner_ids",
    ],
    "resolve_partner_log" => [
        "partner_ids",
    ],
    "compose_partner_log" => [
        "cost_partner_id",
        "get_partner_id",
    ],
    "partner_reborn_log" => [
        "target_partner_id",
        "cost_partner_id",
        "reborn",
    ],
    "plot_log" => [
        "level",
        "win_flag",
    ],
    "tower_log" => [
        "level",
        "win_flag",
    ],
    "alchemy_log" => [
        "op_type",
        "room_type",
        "items",
    ],
    "eqm_strenght_log" => [
        "eqm_id",
        "succ",
        "strenght_eqm_id",
        "level",
        "strenght_id",
    ],
    "eqm_mount_log" => [
        "eqm_id",
        "stone_list",
        "mount_eqm_id",
    ],
    "stone_compose_log" => [
        "cost_item_id",
        "cost_item_num",
        "succ",
        "get_item_id",
        "get_item_num",
    ],
    "rune_compose_log" => [
        "cost_item_id",
        "cost_item_uids",
        "succ",
        "get_item_id",
        "get_item_uid",
    ],
    "rune_recast_log" => [
        "item_uid",
        "item_id",
        "attr_recast_store_id",
        "skill_recast",
    ],
    "godfloor_rob_log" => [
        "reborn",
        "win_flag",
        "enemy_uid",
        "enemy_nick",
        "rewards",
        "reward_type",
    ],
    "arena_log" => [
        "win_flag",
        "enemy_uid",
        "enemy_nick",
        "win_point",
        "total_point",
    ],
    "private_boss_log" => [
        "level",
        "win_flag",
    ],
    "world_boss_log" => [
        "level",
        "win_flag",
    ],
    "endless_log" => [
        "level",
        "win_flag",
    ],
    "union_boss_log" => [
        "level",
        "win_flag",
        "union_id",
        "hp_max",
        "left_hp",
        "hurt",
        "total_hurt",
    ],
    "union_pk_sign_log" => [
        "cave_id",
        "union_id",
        "sign_type",
        "is_leader",
    ],
    "union_pk_log" => [
        "zone_id",
        "cave_id",
        "win_flag",
        "union_id",
    ],
    "chat_log" => [
        "send_type",
        "sub_type",
        "sender_uid",
        "sender_nick",
        "sender_zone_id",
        "recver_uid",
        "recver_nick",
        "recver_zone_id",
        "content",
        "content_id",
        "emoji_id",
        "share_id",
        "share_base_id",
        "share_url",
    ],
];
